### ISSUE TITLE
Old Epic

### ISSUE THREAD

**Issue by matmair** [matmair/inventree-approvals#1]
The following items should be relatively easy to implement - if the need for them arises. The code base was designed with them in mind.

```[tasklist]
### Rules
- [x] min number of approvers
- [x] max number of deniers
- [ ] quorum
- [ ] user attribute-based rules
- [ ] time limits on cases
```

```[tasklist]
### Workflow optimisation
- [ ] dynamic template selector
- [ ] revocation/removal of approvals
- [ ] interactive slack/teams messages
- [ ] invite/request approval
- [ ] template import/export
```

```[tasklist]
### Advanced feature
- [ ] rule templates
- [ ] events/tracking of any changes (see stock tracking)
- [ ] notifications for approvals
```

These features could be very interesting for Change Managment / ECO / ECR and maybe also for usage in plugins. 

Repost of https://github.com/inventree/InvenTree/issues/5097
